### ISSUE TITLE
How to implement in readme

### ISSUE THREAD

**Issue by noffice** [joey-beech-it/Snippet-RteLinkSyntaxUpdater-TYPO3-V10#1]
Hi,

sorry - could you add a short descreption how I can implement the snippet to my installation?

thx

**Comment by joey-bolts** [comment]
@noffice Check the README.md again.

README.md in combination with https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/UpdateWizards/Creation.html should be sufficient. 

Goodluck
