### ISSUE TITLE
PHP Warning: Undefined array key "backend_layout"

### ISSUE THREAD

**Issue by Alagts** [joey-beech-it/Snippet-RteLinkSyntaxUpdater-TYPO3-V10#2]
TYPO3 12 & PHP 8.2

#1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "backend_layout" in /var/www/html/packages/xxxxxx/Classes/Update/RteLinkSyntaxUpdater.php line 108

**Comment by joey-bolts** [comment]
@Alagts 

Thank you Sandra
